import { Profile } from "components"
import Head from "next/head"

export default function Home() {
	return (
		<>
			<Head>
				<title>Broadcaster API</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.png" />
			</Head>

			<main className="p-4 sm:p-12 min-h-screen w-full flex-col gap-8 flex items-center justify-center">
				<h1 className="text-xl sm:text-2xl max-w-3xl text-center">
					This app shows how we can use{" "}
					<a
						className="inline text-blue-500 font-semibold"
						href="https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API"
					>
						BroadcastChannel API
					</a>{" "}
					to detect dublicate tabs. Open this app in another tab and you will
					see a modal. Click on{" "}
					<span className="inline font-semibold">{" Use here "}</span>
					to use this app in this tab.
				</h1>

				<Profile />
			</main>
		</>
	)
}
